---
title: "Main Text"
author: "Ruoyu Wu"
date: "2023-06-30"
output:
  html_document: default
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE,  warning = FALSE, message = FALSE)
source("code/0_utils.R")
df_smooth <- read_rds(str_c(.path$dat_process, "2023-04-25/fill_smooth_offset.rds"))
df_metrics <- read_rds(str_c(.path$dat_process, "2023-04-25/metrics_daymet.rds"))
```

# Fig. 1

```{r calendar-fig, fig.width=8, fig.height=8*1.618, fig.cap = "Pollen calendar for all the stations that met our criteria. \nDaily long-term mean of fungal spore concentration, 2003-2022."}
source("code/18_results_temporal_calendar_spatial_variability.R")
p_calendar
```

# Fig. 2

```{r metrics-fig, fig.cap="100% data completeness", fig.height=11*0.618, fig.width=11}
pct = 1
source("code/8g_explore_summary_metrics.R")
p_metrics
```

# Fig. 3

```{r trend-fig, fig.width=8, fig.height=10*1.618}
pct = 1
source("code/19_results_lme_trend.R")
grid.arrange(p_trend_c1, p_trend_c2, ncol=2)
```

# Fig. 4

```{r climate-fig, fig.height=12*3, fig.width=12}
source("code/20_results_lm_climate.R")
grid.arrange(
  p_climate_a1, p_climate_a2,
  p_climate_b1, p_climate_b2,
  p_climate_c1, p_climate_c2,
  p_climate_d1, p_climate_d2,
  p_climate_e1, p_climate_e2,
  p_climate_f1, p_climate_f2,
  p_climate_g1, p_climate_g2,
  ncol = 2,
  nrow = 7,
  widths = c(3, 1),
  heights = c(1, 1, 1, 1, 1, 1, 1)
  )
```
