---
title: "main text"
author: "Ruoyu Wu"
date: "2024-02-07"
output:
  html_document: default
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE, process=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, warning = FALSE, message = FALSE, process=FALSE)
source("~/Github/spore_phenology/code/0_utils.R")
df_ana <- read_rds(str_c(.path$dat_process, "2023-04-25/dat_ana.rds"))
```

# Fig. metrics
```{r fig-metrics, fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE, fig.cap="Definition and numerical summary of ten fungal spore metrics. The annotation of ten fungal spore metrics (A). Orange indicates metrics defined in the ecological approach, while dark red indicates metrics defined in the public health approach. Each box represents each metric's interquartile range (IQR), with the median value indicated by the line inside. Whiskers extend to the minimum and maximum values within 1.5 times the IQR, while points beyond the whiskers are considered outliers. Phenology metrics are in the unit of day of spore year (DOY) (C), while intensity metrics are in the unit of grains m^-3 or grains m^-3 days, displayed on a natural logarithm-transformed scale (B) (D)."}
source("~/Github/spore_phenology/code/analysis/plot_metrics.R")
p_metrics
```

```{r fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE}
p_metrics0
```

```{r fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE}
p_metrics1
```

```{r fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE}
p_metrics2
```

```{r fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE}
p_metrics3
```

```{r fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE}
p_metrics4
```

```{r fig.height=11, fig.width=11, echo = FALSE, message=FALSE, warning=FALSE, process=FALSE}
p_metrics5
```
